project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Hannah Loder" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Hannah's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Loder_Hannah_Creative_Resume_2023.pdf
        text: Resumé
      - portfolio.qmd
      - walkthrough.qmd
      - testpage.qmd
      - classarticle.qmd
      - mapexample.qmd
      - vaelectionproject.qmd

      

      


format:
  html:
    theme: minty
    css: styles.css
    toc: true



