---
title: "Article Example"
---

I wrote the following article for my cultural reporting class in the fall of 2022. The article shares the stories of people in D.C. who have volunteered to help the migrants who were bussed there by conservative politicians in Texas and Arizona. I spoke with volunteers and experts for the article.

## The network that stepped up to help migrants in DC

The buses started to arrive in April. By June and July, there were about two buses per day bringing more than 50 migrants who crossed the border in Texas and Arizona to the District of Columbia. But there were organizations waiting to help them here as much as possible. 

Francisco Lara is one of the volunteers who helped receive migrants at Union Station during the summer.

\"I volunteered a few times to receive migrants because I felt like I needed to,\" Lara said. \"It's something that's so close to me that I felt like I had a responsibility to go help these people.\"

In 2015, Lara and his family left Venezuela to move to Boston because of the worsening situation in his home country. He said he was fortunate enough to take a plane and wanted to help the migrants who have had much more difficult journeys. 

\"They\'re crossing through treacherous terrain, which includes the Darién River, which is between Panama and Colombia, an area that was previously never crossed by migrants that were trying to reach the U.S.,\" Lara said. \"But due to the dire humanitarian situation in the country, they felt like they\'ve had to.\"

Lara volunteered with [Humanitarian Action](https://humanitarianactionorg.com/), an organization working to help communities facing humanitarian crises. According to the [UN Refugee Agency](https://www.unhcr.org/en-us/venezuela-emergency.html), there are more than 6.8 million refugees and migrants from Venezuela across the world and more than 2.4 million Venezuelans live \"under legal forms of stay in the Americas.\"

Another organization that mobilized to support the migrants in D.C. is [Sanctuary DMV](https://twitter.com/SanctuaryDMV?s=20&t=-Kyxj6sKIM_Tzm7H7WBbAw), a mutual aid group. Diana Pardo Pedraza, who has a doctorate in cultural studies and is an assistant professor of anthropology and international affairs at The George Washington University, started volunteering with the group in April. 

\"It has been a great experience because despite the fact that these migrants have suffered so much. I\'m amazed by their endurance and their survival and their high spirit, but also how the community here in D.C. has come together to support them and do whatever they can with the few resources that we have available,\" Pardo said. 

Sanctuary DMV has had no aid from the federal government or the District until very recently, Pardo said. 

On September 20, D.C. Mayor Muriel E. Bowser (D) [established the Office of Migrant Services](https://mayor.dc.gov/release/mayor-bowser-establishes-office-migrant-services), citing the 9,400 migrants who Texas and Arizona have bussed to the District since the spring. The D.C. Council approved the order of the mayor on September 21, but there is no clear timeline provided by the government for the creation of the office. 

Pardo, who is Colombian, speaks Spanish and said she and the other volunteers explain to the migrants where they ended up and help connect them to support, which often means helping buy them a bus ticket to get them to where they want to go. For migrants who stay in D.C., Pardo said they try to set them up with housing and job connections. 

\"We welcome them,\" Pardo said. \"We ask their consent to go to a church or a space of respite, where we provide some food, some water, coffee, clothes that have been donated. We help them as much as we can to go to their final destination.\"

While the migrants arrived in D.C. after Republican leaders transported them in an effort to shift the responsibility of migrant reception to northern states and the District, Manuel Cuellar, who has a doctorate in Hispanic languages and literatures and teaches a class at The George Washington University called \"Latin/x American Migrations,\" said this has actually been helpful for many migrants.

\"Most of the migrants usually have communities that are hoping that they arrive and are waiting for them,\" Cuellar said. \"Inadvertently, I believe that at times they\'ve helped them in their journeys, these political stunts, by bringing them further out north, so they get closer to their families where they want to go.\"

Cuellar said many migrants cross into the United States with a goal of ending up in New York. Migrants who [arrived in Martha\'s Vineyard](https://www.npr.org/2022/09/15/1123109768/migrants-sent-to-marthas-vineyard) on September 14 by plane after Florida Gov. Ron DeSantis paid for their flights from San Antonio, Texas, were a lot closer to New York than if they had stayed in Texas.

Cecilia Brennan, a master\'s student in mental health counseling, has an internship at Martha\'s Vineyard Community Services. She said she worked closely with the migrants after they arrived at the center and that the community rallied to support them.

\"They really benefited,\" Brennan said. \"They thanked Ron DeSantis --- like they're saying, \'Well, thanks for sending us here.\' The political stunt sort of backfired.\"

Another issue many of the migrants have needed help navigating is immigration court dates. Many of the migrants have been assigned court dates in municipalities across the country, making it difficult for them to make it to the hearing to be granted asylum and a working visa. Lara said he met one migrant in D.C. who had been given a court date in Los Angeles shortly after they had arrived in the District.  

There are organizations, like Ayuda DC, that offer legal support to migrants in the District. 

The difficulties in Venezuela are far from over, Lara said. The way to bring change is to elect a new leader, but the next election is not until 2024, he said. 

Until that time, Lara said it is important to be kind. 

\"If you ever see someone who\'s in need, in this case (who) is a migrant, get them food from 711 --- something like that,\" Lara said. \"They\'ll really appreciate it. They\'ve been through tough times.\"

\
