---
title: "Essay Example"
---

I wrote this paper for a class titled Media, Technology & Culture in the spring of 2022. This paper centers on the use of memes in popular culture to bring humor into dark situations. While that can be helpful, it can also hide the dangerous potential of those situations. In the essay, I apply the attention crisis to the conversation and use examples of memes about the conflict between Russia and Ukraine to illustrate the possible negative consequences of memes.

## The Potential Harm of Memes in the Midst of the Attention Crisis

Scrolling on social media leads to the bombardment of visual and written content, often with the intention to entertain or inform. This online content zaps people\'s attention and keeps them returning to their favorite apps over and over again. Memes are a large part of this online culture. Jonathan L. Zittrain, in his article \"Reflections on Internet Culture,\" writes that \"an internet meme is a picture or drawing (usually from an unwitting source) that\'s taken on a shared, iconic quality, coupled with a resonating message\" (388). Memes cover all aspects of life and can resonate deeply with one group of people and confuse another. The underlying messages of the memes can sometimes be unrealized as people continuously scroll through them. This continuous scrolling works to further the attention crisis, as Johann Hari says in his article, \"Your attention didn\'t collapse. It was stolen,\" this constant online presence is creating \"an environment in which sustained and deep focus is harder for all of us.\" Without the ability to concentrate deeply on the memes they see on the internet, people are less aware of the negative elements contained in them that can breed a culture of hate and ignorance, as Whitney Phillips discusses in her article, \"It Wasn\'t Just the Trolls: Early Internet Culture, \'Fun,\' and the Fires of Exclusionary Laughter.\" Current events provide a multitude of examples of memes working to find humor in the midst of dark times. This humor, however, can overlook the danger pointed out by such content. A timely example is the critical situation in Ukraine as Russia has invaded the country and declared war. On social media, memes have circulated about the threats of violence for multiple months, using humor to thwart the gravity of the situation. Memes operate within the attention crisis of today and make consumers less aware of their potentially harmful latent messages, as evidenced by examples in the current Ukraine crisis.

First, the attention crisis is deep rooted in society and creates the foundation for the popularity and prominence of memes online. As Hari explains in his piece, concentration is more difficult for people who spend a lot of time online and on social media. He says it is not enough for one person to decide to spend less time online; society has created this attention deficit. In today\'s culture, phones are an integral part of jobs and relationships, making this issue extremely prevalent. When people constantly have their attention pulled from the task at hand, their \"performance drops\" (Hari). Constantly switching from what they are doing to reading texts or looking at memes on social media creates the \"switch-cost effect,\" which means that people lose even more time to refocus after their attention is pulled to their phones (Hari). Memes add to this attention deficit by being easily accessible any time people go on social media. The funny or ironic nature of memes can make them fun to look at and take people\'s attention for a long period of time as they scroll through the thousands of memes available at their fingertips. Memes are also fleeting. One meme does not take too much of a person\'s attention, making it easy to move on as soon as they get bored, which in the attention crisis of today is often. As a result, memes thrive online because of the attention crisis, continuing the cycle of the ever decreasing attention span. 

Next, the nature of internet culture is ironic, creating space for memes to play with difficult themes while not explicitly calling them out. A successful meme, according to Zittrain, \"exposes a truth about something, and in its versatility allows that truth to be captured and applied in new situations\" (389). Playing with truth, allows for memes to bend what is factual for comedic reasons, and the flexibility of memes allows them to be reproducible, adding to the massive amounts of content pulling at people\'s attention online. What results from this is a massive amount of content that is not always true, and when people do not spend a lot of time digesting and dissecting memes, they do not always understand the ironies or messages that the memes share. Similarly, Zittrain writes that \"the retreat into irony, being serious while not taking oneself seriously, is what lends internet culture its power and force\" (391). In this statement, it is clear that memes can sometimes share important messages that expose societal ills in a way that can be funny and provide relief. In fact, internet culture uses that as its driving force. When people do not devote their attention to understanding the ironies, however, memes can breed the hate or societal ills they are trying to expose. In this way, the foundation of internet culture in irony can make it ripe with comedic relief, but it can also make it difficult to unpack the humor from the hate. 

To continue, the multitude of memes that contain dark themes can foster hate, leading to violence and a complacent public. Phillips writes in her article, \"Fun and funny and apparently harmless things have a way of obscuring weapons that privileged people cannot see, because they do not have to see them\" (1). She goes on to discuss the fact that many memes posted between 2008 and 2012 represented middle class, straight, white, male thinking, thus reproducing themes that aligned with that thinking within the online sphere. Memes of that nature reflect a privilege that can have negative consequences for people of color, women and queer people. In those days, hateful content was written off as \"trolling,\" but this trolling created a foundation of hate and effectively \"numbed\" the public from hateful content. When this hate is combined with funny and ironic memes, the message mixes and hate becomes harmless and funny. In the context of the attention crisis of today, these mixed messages blur more, as people do not spend enough time to decipher their true meanings, whether they are truly funny or not. Phillips points to the hateful memes of the past that led to right-wing extremist violence, a group of society that is overwhelmingly white and male. While many people online are not a part of this group, the content still has the power to circulate to the masses, reaching wide audiences that may be susceptible to the messages behind the hateful memes or may be directly attacked by those messages. As a result, the mixture of hate and irony creates an atmosphere where potentially damaging memes have air to breathe. Even laughing at a meme that has hateful leanings creates a public that is desensitized to the hatred, and the underlying resentment has the potential to build and manifest into hate crimes and other violent behavior. Consequently, memes with negative intentions circulate widely on social media, numbing people to their potential harm and continuing to steal their attention away from aspects of life that are less damaging. 

Further, Phillips focused on content from ten or more years ago, but memes are still as prevalent today, if not more so. As attention spans shorten and memes continue to have a large online presence, using humor and irony in the midst of difficult situations is almost the status quo. The implications of this could be great if people do not take potentially dangerous information seriously. A prime example of this is the current crisis in Ukraine. With threats of violence from Russia, Ukraine\'s own verified Twitter acount, \@Ukraine, posted a meme on December 27, 2021, that says, \"Putin\'s real fears...\" along the top of the image. Next to the image of a fluffy, pet dog it reads, \"Ukraine in NATO.\" To the right of the pet dog is a scary-looking, wolflike monster with the words, \"Human rights, free press, fair elections.\" This meme calls out Russia\'s politics using humor. With Ukraine posting content like this, the fears of an invasion by Russia are reduced to a funny meme, effectively lightening the situation. While there is power in finding the funny in the midst of difficult times, memes like this have the potential to numb the public to the threats from Russia. They keep the threat as a hypothetical, a joke. On January 13, 2022, \@Ukraine tweeted another meme with a still frame from an episode of The Simpsons and the words, \"Stop saying \'Ukraine Crisis.\' There is no crisis. There is a bad neighbor.\" Again, this meme adds humor to a grave situation that needs to be regarded as such. An invasion by Russia inevitably means lives lost and destruction of infrastructure. When Ukraine itself is tweeting this, perhaps in an effort to be relatable, it is downplaying the potentially detrimental situation for which people should be preparing.

Lastly, \@Ukraine tweeted a cartoon image of Hitler caressing Putin\'s face on February 24, 2022, after Putin declared war in a televised address over the night of Wednesday, February 23. Three hours after posting the image, \@Ukraine tweeted, \"This is not a \'meme\', but our and your reality right now.\" These words put the non-meme that Ukraine posted into a more serious light, substantially taking the humor out of it. The fact that the account needed to clarify its intention adds to the potentially harmful nature of memes. The irony can be overlooked, and people can take them at face value, effectively missing the point. Ukraine\'s clarification is proof of that. The potential of violence at the hands of Russia in Ukraine mounted over the past few months, but with the use of memes by thousands of users, including Ukraine\'s own account, that violence was reduced to comedy and a far-off threat. Then, when the violence came, a meme, or as Ukraine put it, a non-meme, needed to be explained for the seriousness it represents, seriousness that was overlooked in the comedy. Accordingly, the example of Ukraine\'s Twitter account is a modern representation of the way memes can represent, or even warn of violence and hatred, and not be taken seriously in this digital age. 

In conclusion, the current internet culture uses memes as a form of therapy, a way to point out the irony while detaching from the difficult ideas that serve as inspiration for them. While memes may seem harmless, when their hidden messages are overlooked, they can be misinterpreted and potentially lead to violence or unimagined hatred. This can be especially harmful in the attention crisis that exists today. People\'s focus is constantly pulled in many directions, one of its largest distractions being meme culture. The potential for danger behind memes can be seen in Ukraine\'s memes about Russia that removed the threat of danger through humor, until that danger was realized in a declaration of war. As Ukraine rallies support after Russia\'s invasion, memes continue to circulate online. As people lose their homes, their livelihoods, their lives, people halfway across the world see a meme about Ukraine on social media, whether it is one that Ukraine posted itself or one of the thousands of others. As they see this meme, they are removed from the true atrocities, and they laugh. They laugh as bombs go off in Kyiv and people flee their homes. 

###### Works Cited

###### Україна, Ukraine. \"Pic.twitter.com/Amgxnggjik.\" Twitter, Twitter, 13 Jan. 2022, <https://twitter.com/Ukraine/status/1481536598760173569?s=20&t=AHUjOFppUbT6ckDOxvZEow>. 

###### Україна, Ukraine. \"Pic.twitter.com/ga1kbRAt97.\" Twitter, Twitter, 27 Dec. 2021, <https://twitter.com/Ukraine/status/1475466172699226118?s=20&t=AHUjOFppUbT6ckDOxvZEow.> 

###### Україна, Ukraine. \"Pic.twitter.com/IAQFBPAYQZ.\" Twitter, Twitter, 24 Feb. 2022, <https://twitter.com/Ukraine/status/1496716168920547331?s=20&t=AHUjOFppUbT6ckDOxvZEow>. 

\
